add_conan_package(tsl-hat-trie 0.6.0)
find_package(tsl-array-hash MODULE REQUIRED)
find_package(tsl-hat-trie MODULE REQUIRED)
include_directories(BEFORE SYSTEM ${tsl_hat_trie_INCLUDE_DIRS} ${tsl_array_hash_INCLUDE_DIRS})
add_library(tsl_hat_trie INTERFACE)
add_library(tsl::tsl_hat_trie ALIAS tsl_hat_trie)
