add_conan_package(tsl-hat-trie 0.6.0)
find_package(tsl-array-hash MODULE REQUIRED)
find_package(tsl-hat-trie MODULE REQUIRED)
include_directories(BEFORE SYSTEM ${tsl_hat_trie_INCLUDE_DIRS} ${tsl_array_hash_INCLUDE_DIRS})
set(TSL_HAT_TRIE_TARGET tsl::hat_trie)
