include(${CMAKE_CURRENT_LIST_DIR}/check_san_option.cmake)

check_san_option("ASAN")
set(ASAN ${SAN_OPTION})
check_san_option("LSAN")
set(LSAN ${SAN_OPTION})
check_san_option("MSAN")
set(MSAN ${SAN_OPTION})
check_san_option("TSAN")
set(TSAN ${SAN_OPTION})
check_san_option("UBSAN")
set(UBSAN ${SAN_OPTION})

message(STATUS "ASAN=${ASAN} LSAN=${LSAN}")

if(ASAN)
  print("Address Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_asan.cmake)
endif()
if(LSAN)
  print("Leak Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_lsan.cmake)
endif()
if(MSAN)
  print("Memory Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_msan.cmake)
endif()
if(TSAN)
  print("Thread Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_tsan.cmake)
endif()
if(UBSAN)
  print("Undefined Behavior Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_ubsan.cmake)
endif()
